<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ravi" failures="1" tests="7" name="Teastng.TestngAssertions" time="0.053" errors="0" timestamp="2023-04-01T20:50:48 IST" skipped="0">
  <testcase classname="Teastng.TestngAssertions" name="test2" time="0.003"/>
  <system-out>
    <![CDATA[running test2 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test3" time="0.004"/>
  <system-out>
    <![CDATA[running test3 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test1" time="0.023"/>
  <system-out>
    <![CDATA[running test1 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test6" time="0.005"/>
  <system-out>
    <![CDATA[running test6 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test5" time="0.002"/>
  <system-out>
    <![CDATA[running test5 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test7" time="0.008">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Teastng.TestngAssertions.test7(TestngAssertions.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test7 -->
  <system-out>
    <![CDATA[running test7 method]]>
  </system-out>
  <testcase classname="Teastng.TestngAssertions" name="test4" time="0.008"/>
  <system-out>
    <![CDATA[running test4 method]]>
  </system-out>
</testsuite> <!-- Teastng.TestngAssertions -->
